name: Deploy To S3

on:
    push:
        branches: 
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: AWS Credentials Configure
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: 'ap-south-1'

            - name: Push to S3
              run: aws s3 sync . s3://adb-s3-magic-magic --delete